version: "3"

services:
  angular:
    image: wizofgoz/evecommander-web:master
    environment:
      VIRTUAL_HOST: "${DOMAIN_NAME_PREFIX}${DOMAIN_NAME_BASE}"

  php-nginx:
    image: "wizofgoz/evecommander-nginx:${BRANCH}-latest"
    environment:
      VIRTUAL_HOST: "${DOMAIN_NAME_PREFIX}api.${DOMAIN_NAME_BASE}"
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: "wizofgoz/evecommander-php:${BRANCH}-latest"
    env_file: "${PHP_ENV_PATH}"
    ports:
      - "9000:9000"
    volumes:
      - localphp:/var/www/html/storage
    links:
      - pgsql
      - redis

  cron:
    image: "wizofgoz/evecommander-php:${BRANCH}-latest"
    env_file: "${PHP_ENV_PATH}"
    command: ["/bin/sh", "-c", "env /bin/bash -o posix -c 'export -p' > /etc/cron.d/project_env.sh && chmod +x /etc/cron.d/project_env.sh && crond -l 2 -f"]
    volumes:
      - localphp:/var/www/html/storage
    links:
      - pgsql
      - redis

  worker:
    image: "wizofgoz/evecommander-php:${BRANCH}-latest"
    env_file: "${PHP_ENV_PATH}"
    depends_on:
      - redis
    command: ["php", "artisan", "queue:work"]
    volumes:
      - localphp:/var/www/html/storage
    links:
      - pgsql
      - redis

  pgsql:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${PGSQL_DATABASE}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
    volumes:
      - localpgsql:/var/lib/postgresql/data

  echo:
    image: lagun4ik/laravel-echo-server
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./echo/:/app/
    links:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - localredis:/data

volumes:
  localphp:
    driver: "local"

  localpgsql:
    driver: "local"

  localredis:
    driver: "local"

networks:
  default:
    external:
      name: service-tier