version: "2"
services:
  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy/vhost.d:/etc/nginx/vhost.d"
      - "./proxy/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/certs:/etc/nginx/certs"
    depends_on:
      - php-nginx
    networks:
      - docker-network

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - nginx-proxy

  frontend:
    container_name: angular
    image: wizofgoz/evecommander-web:latest
    environment:
      VIRTUAL_HOST: evecommander.com
      LETSENCRYPT_HOST: evecommander.com
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"

  php-nginx:
    container_name: php-nginx
    image: wizofgoz/evecommander-nginx:latest
    environment:
      VIRTUAL_HOST: api.evecommander.com
      LETSENCRYPT_HOST: api.evecommander.com
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    depends_on:
      - php-fpm
    networks:
      - docker-network

  php-fpm:
    container_name: php-fpm
    image: wizofgoz/evecommander-php:latest
    env_file: "${PHP_ENV}"
    ports:
      - "9000:9000"
    volumes:
      - localphp:/var/www/html/storage
    links:
      - redis
    networks:
      - docker-network

  cron:
    container_name: cron
    image: wizofgoz/evecommander-php:latest
    command: ["/bin/sh", "-c", "env /bin/bash -o posix -c 'export -p' > /etc/cron.d/project_env.sh && chmod +x /etc/cron.d/project_env.sh && crontab /etc/cron.d/artisan-schedule-run && cron && tail -f /var/log/cron.log"]
    volumes:
      - localphp:/var/www/html/storage
    links:
      - redis
    networks:
      - docker-network

  worker:
    container_name: worker
    image: wizofgoz/evecommander-php:latest
    depends_on:
      - redis
    command: ["php", "artisan", "queue:work"]
    volumes:
      - localphp:/var/www/html/storage
    links:
      - redis
    networks:
      - docker-network

  pgsql:
    container_name: pgsql
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${PGSQL_DATABASE}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
    volumes:
      - localpgsql:/var/lib/postgresql/data
    networks:
      - docker-network

  echo:
    container_name: echo
    image: lagun4ik/laravel-echo-server
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./echo/:/app/
    links:
      - redis
    networks:
      - docker-network

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - localredis:/data
    networks:
      - docker-network

volumes:
  localphp:
    driver: "local"

  localpgsql:
    driver: "local"

  localredis:
    driver: "local"

networks:
  docker-network:
    driver: bridge